 
- name: create container
  become: yes
  hosts: localhost
  tasks:
  - name: supprimer conteneur tomcat s'il exist
    command: docker rm --force tomcat
  - name: build image
    command: docker build -t tomcat /opt/ansible/

  - name: tag image
    command: docker image tag tomcat souaddjerfi/tomcat:latest
  - name: push image
    command: docker push souaddjerfi/tomcat:latest

- name: pull and run image
  become: yes
  hosts: 172.31.50.133
  tasks: 
  - name: pull image
    command: docker pull souaddjerfi/tomcat:latest
  - name:  run dans dockerhost 
    command: docker run -d --name tomcat -p 8082:8080 souaddjerfi/tomcat:latest

